apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerinformation-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demopage
  template:
    metadata:
      labels:
        app: demopage
    spec:
      containers:
        - name: addressbook-container
          image: nishant1784/demopage:0.1
          ports:
            - containerPort: 8080
